### ISSUE TITLE
Dataframe udseende i 01-intro-to-r

### ISSUE THREAD

**Issue by enerammer** [KUBDatalab/R-intro#47]
Er det ikke muligt at sørge for at titlerne er venstre stillet?

**Comment by chrbknudsen** [comment]
Hvis vi kan finde den rette css-tag skulle noget i denne retning kunne gøre det:
```{css, echo=FALSE}
table th {
    text-align: left;
}
```

Det ser dog ud til at tabellen her laves som ren tekst, uden brug af table tags. Og så bliver det svært.

Vi kan bruge knitr::kable() til at gøre ting. Men uanset hvad, vil venstrestilling føre til at det ser anderledes ud end hvad de studerende præsenteres for på skærmen, hvor det er konsekvent højrestillet.

**Comment by enerammer** [comment]
Lad os lukke denne og sige at det er fint.
